import React from "react";
import { Sheet, Button, Page, Text, useNavigate } from "zmp-ui";
import { useAuthRequest } from "@/hooks/getUserAuth";
import { ComboboxDemo } from "@/components/combobox-demo";

const AboutPage: React.FunctionComponent = (props) => {
  const [actionSheetOpened, setActionSheetOpened] = React.useState(false);
  const { authData, request } = useAuthRequest();
  const navigate = useNavigate();
  return (
    <Page className="page">
      <div className="section-container">
        <Text>This mini app was generated by zmp-cli</Text>
      </div>
      <div>
        <ComboboxDemo />
      </div>
      <div>
        <Button
          variant="secondary"
          fullWidth
          onClick={() => setActionSheetOpened(true)}
        >
          Back
        </Button>
        <Button variant="primary" fullWidth onClick={() => request()}>
          get user info
        </Button>
      </div>
      <Sheet.Actions
        visible={actionSheetOpened}
        onClose={() => setActionSheetOpened(false)}
        actions={[
          [
            {
              text: "Go back",
              onClick: () => {
                navigate(-1);
              },
            },
            {
              text: "Action 1",
              close: true,
            },
            {
              text: "Action 2",
              close: true,
            },
          ],
          [
            {
              text: "Close",
              close: true,
              danger: true,
            },
          ],
        ]}
      ></Sheet.Actions>
    </Page>
  );
};

export default AboutPage;
